'use client'

import { ShieldCheck, Server, Users, Save, RefreshCw } from 'lucide-react'
import { useState, useEffect } from 'react'

export default function Whitelist() {
  const [protocols, setProtocols] = useState<any[]>([])
  const [agents, setAgents] = useState<any[]>([])
  const [loading, setLoading] = useState(true)
  const [userId, setUserId] = useState<string | null>(null)
  
  // Local state for toggles
  const [whitelistedProtocols, setWhitelistedProtocols] = useState<string[]>([])
  const [whitelistedAgents, setWhitelistedAgents] = useState<string[]>([])
  const [isSaving, setIsSaving] = useState(false)
  const [isSeeding, setIsSeeding] = useState(false)

  useEffect(() => {
    const storedId = localStorage.getItem('sentinel_user_id')
    if (storedId) {
      setUserId(storedId)
    }
  }, [])

  useEffect(() => {
    if (!userId) return;

    async function fetchData() {
      try {
        const apiUrl = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:4000';
        const [protoRes, agentRes, userRes] = await Promise.all([
          fetch(`${apiUrl}/api/protocols`),
          fetch(`${apiUrl}/api/agents`),
          fetch(`${apiUrl}/api/users/${userId}`)
        ])
        
        const protos = await protoRes.json()
        const ags = await agentRes.json()
        const userConfig = await userRes.json()
        
        setProtocols(protos)
        setAgents(ags)
        
        if (userConfig.whitelistedProtocols) setWhitelistedProtocols(userConfig.whitelistedProtocols)
        if (userConfig.whitelistedAgents) setWhitelistedAgents(userConfig.whitelistedAgents)
        
      } catch (e) {
        console.error("Make sure the backend is running", e)
      } finally {
        setLoading(false)
      }
    }
    fetchData()
  }, [userId])

  const getRiskColor = (score: number) => {
    if (score < 20) return 'text-green-400 bg-green-500/10 border-green-500/30';
    if (score < 50) return 'text-yellow-400 bg-yellow-500/10 border-yellow-500/30';
    return 'text-red-400 bg-red-500/10 border-red-500/30';
  };

  const handleSave = async () => {
    if (!userId) return;
    setIsSaving(true);
    try {
      const apiUrl = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:4000';
      await fetch(`${apiUrl}/api/users/${userId}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          whitelistedProtocols,
          whitelistedAgents
        })
      });
      alert('Whitelist Configuration Saved Successfully!');
    } catch (e) {
      console.error(e);
      alert('Failed to save configuration');
    } finally {
      setIsSaving(false);
    }
  };

  const handleSeed = async () => {
    setIsSeeding(true);
    try {
      const apiUrl = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:4000';
      await fetch(`${apiUrl}/api/seed`, { method: 'POST' });
      window.location.reload();
    } catch (e) {
      console.error(e);
    } finally {
      setIsSeeding(false);
    }
  };

  const toggleProtocol = (id: string) => {
    setWhitelistedProtocols(prev => 
      prev.includes(id) ? prev.filter(x => x !== id) : [...prev, id]
    );
  };

  const toggleAgent = (id: string) => {
    setWhitelistedAgents(prev => 
      prev.includes(id) ? prev.filter(x => x !== id) : [...prev, id]
    );
  };

  if (!userId) {
    return <div className="text-center p-12 text-gray-400">Please login on the Dashboard first.</div>
  }

  if (loading) return <div className="text-center p-12 text-gray-400">Loading live data from Venice AI...</div>

  return (
    <div className="space-y-8">
      <div className="flex justify-between items-center">
        <div>
          <h2 className="text-2xl font-bold flex items-center gap-2"><ShieldCheck className="text-blue-500"/> Trust Center & Venice AI Ratings</h2>
          <p className="text-gray-400 mt-2">Manage which protocols and agents are allowed to interact with your funds. Risk scores are dynamically generated by Venice AI.</p>
        </div>
        <button 
          onClick={handleSave}
          disabled={isSaving}
          className="px-6 py-2 bg-blue-600 hover:bg-blue-700 text-white font-bold rounded-lg transition flex items-center gap-2 disabled:opacity-50"
        >
          <Save size={18} /> {isSaving ? 'Saving...' : 'Save Configuration'}
        </button>
      </div>

      <div className="glass-card">
        <div className="flex justify-between items-center mb-6">
          <h3 className="text-xl font-bold flex items-center gap-2"><Server className="text-purple-500"/> Protocol Whitelist</h3>
          {protocols.length === 0 && (
            <button 
              onClick={handleSeed}
              disabled={isSeeding}
              className="px-4 py-1.5 bg-purple-600/20 text-purple-400 hover:bg-purple-600/40 rounded-lg text-sm border border-purple-500/30 flex items-center gap-2 transition"
            >
              <RefreshCw size={14} className={isSeeding ? 'animate-spin' : ''} /> 
              {isSeeding ? 'Syncing...' : 'Sync Venice AI Ratings'}
            </button>
          )}
        </div>
        <div className="grid gap-4">
          {protocols.map(p => (
            <div key={p.id} className="flex flex-col md:flex-row justify-between items-start md:items-center p-4 bg-white/5 border border-white/10 rounded-xl hover:bg-white/10 transition cursor-pointer" onClick={() => toggleProtocol(p.id)}>
              <div className="flex items-center gap-4">
                <input 
                  type="checkbox" 
                  checked={whitelistedProtocols.includes(p.id)}
                  onChange={() => {}} // handled by parent div onClick
                  className="w-5 h-5 rounded border-gray-600 text-blue-500 focus:ring-blue-500 bg-gray-700 cursor-pointer" 
                />
                <div>
                  <h4 className="font-bold text-lg">{p.name}</h4>
                  <p className="text-sm text-gray-400 max-w-xl">Venice AI: &quot;{p.veniceReasoning || 'Risk assessed.'}&quot;</p>
                </div>
              </div>
              <div className="mt-4 md:mt-0 text-right w-full md:w-auto flex justify-end">
                <span className={`px-3 py-1 rounded-full text-xs border ${getRiskColor(p.riskScore)}`}>
                  Risk Score: {p.riskScore}/100
                </span>
              </div>
            </div>
          ))}
          {protocols.length === 0 && <p className="text-gray-500 text-sm">No protocols synced yet. Click "Sync Venice AI Ratings".</p>}
        </div>
      </div>

      <div className="glass-card">
        <h3 className="text-xl font-bold mb-6 flex items-center gap-2"><Users className="text-orange-500"/> Agent Whitelist</h3>
        <div className="grid gap-4">
          {agents.map(a => (
            <div key={a.id} className="flex flex-col md:flex-row justify-between items-start md:items-center p-4 bg-white/5 border border-white/10 rounded-xl hover:bg-white/10 transition cursor-pointer" onClick={() => toggleAgent(a.id)}>
              <div className="flex items-center gap-4">
                <input 
                  type="checkbox" 
                  checked={whitelistedAgents.includes(a.id)}
                  onChange={() => {}} // handled by parent div onClick
                  className="w-5 h-5 rounded border-gray-600 text-blue-500 focus:ring-blue-500 bg-gray-700 cursor-pointer" 
                />
                <div>
                  <h4 className="font-bold text-lg">{a.name}</h4>
                  <p className="text-sm text-gray-400 max-w-xl">Venice AI: &quot;{a.veniceReasoning || 'Trust verified.'}&quot;</p>
                </div>
              </div>
              <div className="mt-4 md:mt-0 text-right w-full md:w-auto flex justify-end">
                <span className={`px-3 py-1 rounded-full text-xs border ${getRiskColor(a.riskScore)}`}>
                  Risk Score: {a.riskScore}/100
                </span>
              </div>
            </div>
          ))}
          {agents.length === 0 && <p className="text-gray-500 text-sm">No agents synced yet. Click "Sync Venice AI Ratings".</p>}
        </div>
      </div>
    </div>
  )
}
