'use client'

import { ShieldCheck, Server, Users } from 'lucide-react'
import { useState, useEffect } from 'react'

export default function Whitelist() {
  const [protocols, setProtocols] = useState<any[]>([])
  const [agents, setAgents] = useState<any[]>([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    async function fetchData() {
      try {
        const apiUrl = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:4000';
        const [protoRes, agentRes] = await Promise.all([
          fetch(`${apiUrl}/api/protocols`),
          fetch(`${apiUrl}/api/agents`)
        ])
        const protos = await protoRes.json()
        const ags = await agentRes.json()
        setProtocols(protos)
        setAgents(ags)
      } catch (e) {
        console.error("Make sure the backend is running on port 4000!", e)
      } finally {
        setLoading(false)
      }
    }
    fetchData()
  }, [])

  const getRiskColor = (score: number) => {
    if (score < 20) return 'text-green-400 bg-green-500/10 border-green-500/30';
    if (score < 50) return 'text-yellow-400 bg-yellow-500/10 border-yellow-500/30';
    return 'text-red-400 bg-red-500/10 border-red-500/30';
  };

  if (loading) return <div className="text-center p-12 text-gray-400">Loading live data from Venice AI...</div>

  return (
    <div className="space-y-8">
      <div>
        <h2 className="text-2xl font-bold flex items-center gap-2"><ShieldCheck className="text-blue-500"/> Trust Center & Venice AI Ratings</h2>
        <p className="text-gray-400 mt-2">Manage which protocols and agents are allowed to interact with your funds. Risk scores are dynamically generated by Venice AI.</p>
      </div>

      <div className="glass-card">
        <h3 className="text-xl font-bold mb-6 flex items-center gap-2"><Server className="text-purple-500"/> Protocol Whitelist</h3>
        <div className="grid gap-4">
          {protocols.map(p => (
            <div key={p.id} className="flex flex-col md:flex-row justify-between items-start md:items-center p-4 bg-white/5 border border-white/10 rounded-xl">
              <div className="flex items-center gap-4">
                <input type="checkbox" defaultChecked={true} className="w-5 h-5 rounded border-gray-600 text-blue-500 focus:ring-blue-500 bg-gray-700" />
                <div>
                  <h4 className="font-bold text-lg">{p.name}</h4>
                  <p className="text-sm text-gray-400 max-w-xl">Venice AI: &quot;{p.veniceReasoning || 'Risk assessed.'}&quot;</p>
                </div>
              </div>
              <div className="mt-4 md:mt-0 text-right">
                <span className={`px-3 py-1 rounded-full text-xs border ${getRiskColor(p.riskScore)}`}>
                  Risk Score: {p.riskScore}/100
                </span>
              </div>
            </div>
          ))}
          {protocols.length === 0 && <p className="text-gray-500 text-sm">No protocols synced yet. Run the backend seeder.</p>}
        </div>
      </div>

      <div className="glass-card">
        <h3 className="text-xl font-bold mb-6 flex items-center gap-2"><Users className="text-orange-500"/> Agent Whitelist</h3>
        <div className="grid gap-4">
          {agents.map(a => (
            <div key={a.id} className="flex flex-col md:flex-row justify-between items-start md:items-center p-4 bg-white/5 border border-white/10 rounded-xl">
              <div className="flex items-center gap-4">
                <input type="checkbox" defaultChecked={true} className="w-5 h-5 rounded border-gray-600 text-blue-500 focus:ring-blue-500 bg-gray-700" />
                <div>
                  <h4 className="font-bold text-lg">{a.name}</h4>
                  <p className="text-sm text-gray-400 max-w-xl">Venice AI: &quot;{a.veniceReasoning || 'Trust verified.'}&quot;</p>
                </div>
              </div>
              <div className="mt-4 md:mt-0 text-right">
                <span className={`px-3 py-1 rounded-full text-xs border ${getRiskColor(a.riskScore)}`}>
                  Risk Score: {a.riskScore}/100
                </span>
              </div>
            </div>
          ))}
          {agents.length === 0 && <p className="text-gray-500 text-sm">No agents synced yet. Run the backend seeder.</p>}
        </div>
      </div>
    </div>
  )
}
